// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuizApp.DAL;

#nullable disable

namespace QuizApp.Migrations
{
    [DbContext(typeof(QuizDbContext))]
    [Migration("20251023151416_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true);

            modelBuilder.Entity("QuizApp.Models.FillInTheBlank", b =>
                {
                    b.Property<int>("FillInTheBlankId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CorrectAnswer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("QuizId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuizQuestionNum")
                        .HasColumnType("INTEGER");

                    b.HasKey("FillInTheBlankId");

                    b.HasIndex("QuizId");

                    b.ToTable("FillInTheBlankQuestions");
                });

            modelBuilder.Entity("QuizApp.Models.FillInTheBlankAttempt", b =>
                {
                    b.Property<int>("FillInTheBlankAttemptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("AnsweredCorrectly")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FillInTheBlankId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuizAttemptId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuizQuestionNum")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserAnswer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("FillInTheBlankAttemptId");

                    b.HasIndex("QuizAttemptId");

                    b.ToTable("FillInTheBlankAttempts");
                });

            modelBuilder.Entity("QuizApp.Models.FlashCard", b =>
                {
                    b.Property<int>("FlashCardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AnsweredCorrectly")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BackgroundColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("QuizId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuizQuestionNum")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowAnswer")
                        .HasColumnType("INTEGER");

                    b.HasKey("FlashCardId");

                    b.HasIndex("QuizId");

                    b.ToTable("FlashCards");
                });

            modelBuilder.Entity("QuizApp.Models.FlashCardQuiz", b =>
                {
                    b.Property<int>("FlashCardQuizId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NumOfQuestions")
                        .HasColumnType("INTEGER");

                    b.HasKey("FlashCardQuizId");

                    b.ToTable("FlashCardQuizzes");
                });

            modelBuilder.Entity("QuizApp.Models.Matching", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrectAnswer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("QuizId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuizQuestionNum")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalRows")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("QuizId");

                    b.ToTable("MatchingQuestions");
                });

            modelBuilder.Entity("QuizApp.Models.MatchingAttempt", b =>
                {
                    b.Property<int>("MatchingAttemptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AmountCorrect")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("AnsweredCorrectly")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MatchingId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuizAttemptId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuizQuestionNum")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalRows")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserAnswer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MatchingAttemptId");

                    b.HasIndex("QuizAttemptId");

                    b.ToTable("MatchingAttempts");
                });

            modelBuilder.Entity("QuizApp.Models.MultipleChoice", b =>
                {
                    b.Property<int>("MultipleChoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CorrectAnswer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("QuizId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuizQuestionNum")
                        .HasColumnType("INTEGER");

                    b.HasKey("MultipleChoiceId");

                    b.HasIndex("QuizId");

                    b.ToTable("MultipleChoiceQuestions");
                });

            modelBuilder.Entity("QuizApp.Models.MultipleChoiceAttempt", b =>
                {
                    b.Property<int>("MultiplechoiceAttemptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("AnsweredCorrectly")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MultiplechoiceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuizAttemptId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuizQuestionNum")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserAnswer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MultiplechoiceAttemptId");

                    b.HasIndex("QuizAttemptId");

                    b.ToTable("MultipleChoiceAttempts");
                });

            modelBuilder.Entity("QuizApp.Models.Option", b =>
                {
                    b.Property<int>("OptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MultipleChoiceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("OptionId");

                    b.HasIndex("MultipleChoiceId");

                    b.ToTable("Options");
                });

            modelBuilder.Entity("QuizApp.Models.Quiz", b =>
                {
                    b.Property<int>("QuizId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NumOfQuestions")
                        .HasColumnType("INTEGER");

                    b.HasKey("QuizId");

                    b.ToTable("Quizzes");
                });

            modelBuilder.Entity("QuizApp.Models.QuizAttempt", b =>
                {
                    b.Property<int>("QuizAttemptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumOfCorrectAnswers")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuizId")
                        .HasColumnType("INTEGER");

                    b.HasKey("QuizAttemptId");

                    b.HasIndex("QuizId");

                    b.ToTable("QuizAttempts");
                });

            modelBuilder.Entity("QuizApp.Models.Ranking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrectAnswer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("QuizId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuizQuestionNum")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("QuizId");

                    b.ToTable("RankingQuestions");
                });

            modelBuilder.Entity("QuizApp.Models.RankingAttempt", b =>
                {
                    b.Property<int>("RankingAttemptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AmountCorrect")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("AnsweredCorrectly")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuizAttemptId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuizQuestionNum")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RankingId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserAnswer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RankingAttemptId");

                    b.HasIndex("QuizAttemptId");

                    b.ToTable("RankingAttempts");
                });

            modelBuilder.Entity("QuizApp.Models.Sequence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrectAnswer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("QuizId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuizQuestionNum")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("QuizId");

                    b.ToTable("SequenceQuestions");
                });

            modelBuilder.Entity("QuizApp.Models.SequenceAttempt", b =>
                {
                    b.Property<int>("SequenceAttemptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("AnsweredCorrectly")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuizAttemptId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuizQuestionNum")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SequenceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserAnswer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SequenceAttemptId");

                    b.HasIndex("QuizAttemptId");

                    b.ToTable("SequenceAttempts");
                });

            modelBuilder.Entity("QuizApp.Models.TrueFalse", b =>
                {
                    b.Property<int>("TrueFalseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CorrectAnswer")
                        .HasColumnType("INTEGER");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("QuizId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuizQuestionNum")
                        .HasColumnType("INTEGER");

                    b.HasKey("TrueFalseId");

                    b.HasIndex("QuizId");

                    b.ToTable("TrueFalseQuestions");
                });

            modelBuilder.Entity("QuizApp.Models.TrueFalseAttempt", b =>
                {
                    b.Property<int>("TrueFalseAttemptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("AnsweredCorrectly")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuizAttemptId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuizQuestionNum")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TrueFalseId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UserAnswer")
                        .HasColumnType("INTEGER");

                    b.HasKey("TrueFalseAttemptId");

                    b.HasIndex("QuizAttemptId");

                    b.ToTable("TrueFalseAttempts");
                });

            modelBuilder.Entity("QuizApp.Models.FillInTheBlank", b =>
                {
                    b.HasOne("QuizApp.Models.Quiz", "Quiz")
                        .WithMany("FillInTheBlankQuestions")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("QuizApp.Models.FillInTheBlankAttempt", b =>
                {
                    b.HasOne("QuizApp.Models.QuizAttempt", "QuizAttempt")
                        .WithMany("FillInTheBlankAttempts")
                        .HasForeignKey("QuizAttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuizAttempt");
                });

            modelBuilder.Entity("QuizApp.Models.FlashCard", b =>
                {
                    b.HasOne("QuizApp.Models.FlashCardQuiz", "Quiz")
                        .WithMany("FlashCards")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("QuizApp.Models.Matching", b =>
                {
                    b.HasOne("QuizApp.Models.Quiz", "Quiz")
                        .WithMany("MatchingQuestions")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("QuizApp.Models.MatchingAttempt", b =>
                {
                    b.HasOne("QuizApp.Models.QuizAttempt", "QuizAttempt")
                        .WithMany("MatchingAttempts")
                        .HasForeignKey("QuizAttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuizAttempt");
                });

            modelBuilder.Entity("QuizApp.Models.MultipleChoice", b =>
                {
                    b.HasOne("QuizApp.Models.Quiz", "Quiz")
                        .WithMany("MultipleChoiceQuestions")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("QuizApp.Models.MultipleChoiceAttempt", b =>
                {
                    b.HasOne("QuizApp.Models.QuizAttempt", "QuizAttempt")
                        .WithMany("MultipleChoiceAttempts")
                        .HasForeignKey("QuizAttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuizAttempt");
                });

            modelBuilder.Entity("QuizApp.Models.Option", b =>
                {
                    b.HasOne("QuizApp.Models.MultipleChoice", "MultipleChoice")
                        .WithMany("Options")
                        .HasForeignKey("MultipleChoiceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("MultipleChoice");
                });

            modelBuilder.Entity("QuizApp.Models.QuizAttempt", b =>
                {
                    b.HasOne("QuizApp.Models.Quiz", "Quiz")
                        .WithMany()
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("QuizApp.Models.Ranking", b =>
                {
                    b.HasOne("QuizApp.Models.Quiz", "Quiz")
                        .WithMany("RankingQuestions")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("QuizApp.Models.RankingAttempt", b =>
                {
                    b.HasOne("QuizApp.Models.QuizAttempt", "QuizAttempt")
                        .WithMany("RankingAttempts")
                        .HasForeignKey("QuizAttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuizAttempt");
                });

            modelBuilder.Entity("QuizApp.Models.Sequence", b =>
                {
                    b.HasOne("QuizApp.Models.Quiz", "Quiz")
                        .WithMany("SequenceQuestions")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("QuizApp.Models.SequenceAttempt", b =>
                {
                    b.HasOne("QuizApp.Models.QuizAttempt", "QuizAttempt")
                        .WithMany("SequenceAttempts")
                        .HasForeignKey("QuizAttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuizAttempt");
                });

            modelBuilder.Entity("QuizApp.Models.TrueFalse", b =>
                {
                    b.HasOne("QuizApp.Models.Quiz", "Quiz")
                        .WithMany("TrueFalseQuestions")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("QuizApp.Models.TrueFalseAttempt", b =>
                {
                    b.HasOne("QuizApp.Models.QuizAttempt", "QuizAttempt")
                        .WithMany("TrueFalseQuestionAttempts")
                        .HasForeignKey("QuizAttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuizAttempt");
                });

            modelBuilder.Entity("QuizApp.Models.FlashCardQuiz", b =>
                {
                    b.Navigation("FlashCards");
                });

            modelBuilder.Entity("QuizApp.Models.MultipleChoice", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("QuizApp.Models.Quiz", b =>
                {
                    b.Navigation("FillInTheBlankQuestions");

                    b.Navigation("MatchingQuestions");

                    b.Navigation("MultipleChoiceQuestions");

                    b.Navigation("RankingQuestions");

                    b.Navigation("SequenceQuestions");

                    b.Navigation("TrueFalseQuestions");
                });

            modelBuilder.Entity("QuizApp.Models.QuizAttempt", b =>
                {
                    b.Navigation("FillInTheBlankAttempts");

                    b.Navigation("MatchingAttempts");

                    b.Navigation("MultipleChoiceAttempts");

                    b.Navigation("RankingAttempts");

                    b.Navigation("SequenceAttempts");

                    b.Navigation("TrueFalseQuestionAttempts");
                });
#pragma warning restore 612, 618
        }
    }
}
